### ISSUE TITLE
Adjust documentation

### ISSUE THREAD

**Issue by byjg** [B-Galati/dockerfiles#2]
Could you improve the documentation for Redis Desktop Manager and Skype?

Before execute the docker run command you need to execute.

```
xhost +SI:localuser:root
```

I tried this on ubuntu.

**Comment by B-Galati** [comment]
Hello @byjg,

I will do it ;-) Thanks for your feedback.

**Comment by B-Galati** [comment]
@byjg I added documentation for the whole repository. I don't want to copy paste the info everywhere. In the future I would like to use a template engine system to manage that sort of problem :-)

**Comment by byjg** [comment]
Thank you :)

Em 20 de nov de 2016 9:41 PM, "Benoit GALATI" notifications@github.com
escreveu:
